# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        ls -al
        pwd
        dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
        ls -al
    - name: Build and push docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
        docker build -t randeerdil/asp-dot-net-core-cv .
        docker tag randeerdil/asp-dot-net-core-cv randeerdil/asp-dot-net-core-cv:$IMAGE_TAG
        docker push randeerdil/asp-dot-net-core-cv:$IMAGE_TAG
        echo "The latest docker image has been uploaded to the repo.."
    - name: Test
      run: dotnet test --no-build --verbosity normal
