name: Pipeline Approval

on:
  push:
    branches: [ "teams" ]
  pull_request:
    branches: [ "teams" ]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send approval request
      id: approval
      run: |
        # Use your preferred method to send an approval request to MS Teams
        # Example: Sending a message using cURL
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "Approval Request: Please type 'approve' to approve this pipeline."
        }' '${{ secrets.TEAMS_WEBHOOK_URL }}'
        
    - name: Wait for approval or 10 minutes
      id: wait-for-approval
      run: |
        for i in {1..60}; do
          # Use your preferred method to retrieve messages from MS Teams
          # Example: Retrieving messages using cURL (replace with actual command)
          messages=$(curl -H "Authorization: Bearer $TOKEN" "https://api.teams.microsoft.com/v1.0/me/messages")
          
          # Check if any message contains the approval keyword
          if [[ $messages == *"approve"* ]]; then
            echo "Pipeline approved!"
            exit 0  # Exit with success code
          fi
          
          sleep 10  # Wait for 10 seconds
        done
        
        echo "No approval received within 10 minutes."
        exit 1  # Exit with failure code
        
    - name: Proceed with pipeline
      if: steps.wait-for-approval.outcome == 'success'
      run: |
        # Perform the rest of your pipeline steps here
