name: Pipeline Approval

on:
  push:
    branches: [ "teams" ]
  pull_request:
    branches: [ "teams" ]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send approval request
      run: |
        # Use your preferred method to send an approval request to MS Teams
        # Example: Sending a message using cURL
        curl -X POST -H "Content-Type: application/json" -d '{
          "text": "Approval Request: Please type 'approve' to approve this pipeline."
        }' '${{ secrets.TEAMS_WEBHOOK_URL }}'
        
    - name: Wait for approval
      run: |
        # Wait for 10 minutes (600 seconds)
        sleep 600
        
    - name: Check approval status
      run: |
        # Use your preferred method to retrieve messages from MS Teams
        # Example: Retrieving messages using cURL (replace with actual command)
        messages=$(curl -H "Authorization: Bearer $TOKEN" "https://api.teams.microsoft.com/v1.0/me/messages")
        
        # Check if any message contains the approval keyword
        if [[ $messages == *"approve"* ]]; then
          echo "Pipeline approved!"
          # Perform the rest of your pipeline steps here
        else
          echo "Pipeline rejected!"
          # Handle rejection
        fi
