# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "iis" ]
  pull_request:
    branches: [ "iis" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to IIS
        uses: microsoft/AspNetCore-Runner@v2
        with:
          appPath: './YourAppFolder' # Path to your ASP.NET Core application
          dotnetVersion: '6.x' # Choose the appropriate version
          publishWebProjects: true
          arguments: '--configuration Release'

        env:
          ASPNETCORE_ENVIRONMENT: Production

      - name: Deploy with Web Deploy
        run: |
          msdeploy -verb:sync -source:contentPath="./YourAppFolder/bin/Release/net6.0/publish" -dest:contentPath="Default Web Site/YourApp",ComputerName="https://172.190.58.226:8172/msdeploy.axd?site=YourApp",UserName="iis-github\randeer",Password="VumI3dYhgNncro",AuthType="Basic"

